
name: CI (Lint/Test/Train/Evaluate)

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: ruff check
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Unit tests (pytest)
        run: pytest

  train:
    runs-on: ubuntu-latest
    needs: [lint_and_test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Train
        run: python src/train.py --config configs/train_config.yml

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: artifacts/model.joblib
          if-no-files-found: error
          retention-days: 14

      - name: Upload training report
        uses: actions/upload-artifact@v4
        with:
          name: reports-train
          path: reports/train_metrics.json
          if-no-files-found: error
          retention-days: 14

  evaluate:
    runs-on: ubuntu-latest
    needs: [train]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download model
        uses: actions/download-artifact@v4
        with:
          name: model
          path: artifacts
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
      - name: Evaluate (Gate)
        run: python src/evaluate.py --config configs/train_config.yml --model-path artifacts/model.joblib

      - name: Upload evaluation report
        uses: actions/upload-artifact@v4
        with:
          name: reports-eval
          path: reports/eval_report.json
          if-no-files-found: error
          retention-days: 14
